/**
 * Standard typing test passages
 * Each test has a duration and content
 */
export const texts = [
    {
      // duration: 60,
      tittle: "Standard Test 1",
      content: "Artificial Intelligence (AI) is transforming the web development landscape, making applications smarter, more efficient, and user-friendly. AI-powered tools, such as automated code generators, intelligent chatbots, and personalized recommendation engines, are revolutionizing how developers create and optimize websites. With AI-driven frameworks, developers can automate repetitive tasks like debugging, testing, and performance optimization, significantly reducing development time. Additionally, AI enhances user experience by analyzing behavior patterns and adjusting content dynamically, ensuring a personalized browsing experience. For instance, AI-powered chatbots can provide real-time assistance to users, handling queries efficiently without human intervention. This automation not only improves customer engagement but also reduces operational costs for businesses. The rise of AI-based web development also extends to accessibility, where intelligent algorithms can generate alternative text for images, improve speech recognition, and enable voice navigation for users with disabilities. As AI continues to evolve, it is expected to play a crucial role in enhancing security through anomaly detection and fraud prevention mechanisms. Developers leveraging AI-powered security tools can proactively identify vulnerabilities and mitigate cyber threats before they become critical. While AI cannot replace human creativity, it serves as a powerful assistant that enhances efficiency, innovation, and overall user satisfaction in web development."
    },
    {
      // duration: 180,
      tittle: "Standard Test 2",
      content: "Federated learning (FL) has gained popularity as a privacy-preserving machine learning approach that allows multiple participants to train a shared model without exposing their raw data. However, security challenges, such as adversarial attacks and model inversion threats, continue to pose significant risks. One promising solution to mitigate these risks is Latent Space Projection (LSP), which obfuscates sensitive features in model updates before aggregation. LSP ensures that critical data representations remain hidden, making it difficult for adversaries to reconstruct original inputs from gradients. By transforming input features into an encrypted latent space, LSP provides an additional layer of security without significantly affecting model performance. Unlike traditional encryption techniques that can be computationally expensive, LSP maintains computational efficiency while improving privacy preservation. Additionally, LSP can dynamically adjust feature sensitivity, ensuring that only relevant and non-sensitive information is used for training. This adaptability is particularly useful in heterogeneous data environments where different clients may have varying levels of risk exposure. When integrated with Explainable AI (XAI) techniques, LSP further enhances transparency by identifying the most critical features contributing to model predictions. This approach strengthens trust in federated learning systems, making them more resilient against adversarial manipulation while maintaining high utility and privacy guarantees."
    },
    {
      // duration: 300,
      tittle: "Standard Test 3",
      content: "Finding a job can be a time-consuming and stressful process, requiring extensive research, resume tailoring, and application tracking. AI-powered agents are revolutionizing job searching by automating various stages, making the process more efficient and personalized. These intelligent systems analyze job postings, match them with candidates' skills and preferences, and even suggest improvements to resumes and cover letters. AI-driven tools can optimize job applications by tailoring them to specific job descriptions, increasing the chances of passing applicant tracking systems (ATS). Furthermore, conversational AI chatbots assist job seekers by providing real-time feedback, conducting mock interviews, and even negotiating salaries based on market trends. AI agents also help job seekers stay organized by tracking application statuses, scheduling follow-ups, and sending reminders. With advancements in natural language processing (NLP) and machine learning, these agents continuously improve their recommendations based on user interactions, ensuring a more effective job search strategy. Additionally, AI can help detect fraudulent job postings, protecting candidates from scams. As AI technology advances, it is expected to play an even greater role in career development, offering tailored learning paths, networking opportunities, and skill assessments. By automating tedious tasks, AI agents enable job seekers to focus on preparing for their careers."
    }
  ];
  